server:
    port: 8086
    shutdown: graceful
    servlet:
        encoding:
            force: true
            charset: UTF-8

spring:
    datasource:
        url: jdbc:mariadb://localhost:3306/furniture?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: root
        password: 3302
        driver-class-name: org.mariadb.jdbc.Driver

    hikari:
        connection-timeout: 30000
        maximum-pool-size: 10
        minimum-idle: 2

    # JPA ??
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                use_sql_comments: true

    thymeleaf:
        cache: false

    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true

upload:
    path: ${user.dir}/uploads
    url-prefix: /uploads

logging:
    level:
        root: INFO
        org.hibernate: INFO
        org.jooq: INFO

user:
    role:
        admin: "ADMIN"
        general: "GENERAL"
        business: "BISUNESS"